on:
  push:
    branches:
      - master






jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Testing Github action'
        run: pwd

      - name: 'Testing Printing'
        run: echo Menna


      - uses: actions/checkout@v3

      - name: 'After'
        run: ls
